"""Tiny helper for moving the app's texts into string resources.

Strings live in tools/i18n/strings.json (key -> {"en": ..., "ru": ...} or plurals
key -> {"plural": true, "en": {one, other}, "ru": {one, few, many, other}}), and are written to
res/values/strings.xml (English, the default) and res/values-ru/strings.xml.
"""
import json, os, sys
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB = os.path.join(ROOT, "tools/i18n/strings.json")
SRC = os.path.join(ROOT, "app/src/main/java/com/artemiy/player")
RES = os.path.join(ROOT, "app/src/main/res")


def load():
    return json.load(open(DB)) if os.path.exists(DB) else {}


def save(db):
    json.dump(db, open(DB, "w"), ensure_ascii=False, indent=1, sort_keys=True)


def add(key, en, ru):
    db = load()
    if key in db and (db[key]["en"], db[key]["ru"]) != (en, ru):
        raise SystemExit(f"key {key} exists with different text")
    db[key] = {"en": en, "ru": ru}
    save(db)


def plural(key, en, ru):
    db = load()
    db[key] = {"plural": True, "en": en, "ru": ru}
    save(db)


def sub(path, old, new, count=1):
    p = os.path.join(SRC, path)
    s = open(p).read()
    n = s.count(old)
    if n < count:
        raise SystemExit(f"{path}: expected {count}, found {n}: {old[:80]!r}")
    s = s.replace(old, new, count if count > 0 else -1)
    open(p, "w").write(s)


def ensure_import(path, line):
    p = os.path.join(SRC, path)
    s = open(p).read()
    if line in s:
        return
    if "\nimport " in s:
        i = s.index("\nimport ")
        s = s[:i] + "\n" + line + s[i:]
    else:
        i = s.index("\n", s.index("package "))
        s = s[:i] + "\n\n" + line + s[i:]
    open(p, "w").write(s)


def _xml_text(t):
    t = escape(t).replace("'", "\\'").replace('"', '\\"')
    if t.startswith("@") or t.startswith("?"):
        t = "\\" + t
    return t


def variant(key, en_x=None, ru_x=None):
    """The expressive wording of an existing string (only where it differs)."""
    db = load()
    if key not in db:
        raise SystemExit(f"no key {key}")
    if en_x is not None: db[key]["en_x"] = en_x
    if ru_x is not None: db[key]["ru_x"] = ru_x
    save(db)


def edit(key, en=None, ru=None):
    db = load()
    if en is not None: db[key]["en"] = en
    if ru is not None: db[key]["ru"] = ru
    save(db)


def write():
    db = load()
    # The expressive variants live under a private-use region ("XE"): Android falls back to the
    # plain language for every string they don't override.
    for lang, folder in (("en", "values"), ("ru", "values-ru"), ("en_x", "values-en-rXE"), ("ru_x", "values-ru-rXE")):
        out = ['<?xml version="1.0" encoding="utf-8"?>',
               "<!-- Generated by tools/i18n/i18n.py from tools/i18n/strings.json — edit there. -->",
               "<resources>"]
        for key in sorted(db):
            e = db[key]
            if lang not in e:
                continue
            if e.get("plural"):
                out.append(f'    <plurals name="{key}">')
                for q, t in e[lang].items():
                    out.append(f'        <item quantity="{q}">{_xml_text(t)}</item>')
                out.append("    </plurals>")
            else:
                out.append(f'    <string name="{key}">{_xml_text(e[lang])}</string>')
        out.append("</resources>")
        os.makedirs(os.path.join(RES, folder), exist_ok=True)
        open(os.path.join(RES, folder, "strings.xml"), "w").write("\n".join(out) + "\n")
    write_extra_languages(db)
    print(f"{len(db)} strings written")


def read_lang(code):
    """tools/i18n/lang/<code>.txt: one `key = text` per line; plurals as `P key = {json}`."""
    strings, plurals = {}, {}
    for line in open(os.path.join(ROOT, "tools/i18n/lang", code + ".txt"), encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        if line.startswith("P "):
            key, value = line[2:].split(" = ", 1)
            plurals[key.strip()] = json.loads(value)
        else:
            key, value = line.split(" = ", 1)
            strings[key.strip()] = value
    return strings, plurals


def write_extra_languages(db):
    """Every other language, translated in its own file; anything missing falls back to English."""
    folder_of = {"uk": "values-uk", "pl": "values-pl", "es": "values-es", "pt": "values-pt", "fr": "values-fr",
                 "de": "values-de", "it": "values-it", "tr": "values-tr", "ja": "values-ja", "zh": "values-zh",
                 "ko": "values-ko"}
    for code, folder in folder_of.items():
        path = os.path.join(ROOT, "tools/i18n/lang", code + ".txt")
        if not os.path.exists(path):
            continue
        strings, plurals = read_lang(code)
        unknown = (set(strings) | set(plurals)) - set(db)
        if unknown:
            raise SystemExit(f"{code}: unknown keys {sorted(unknown)}")
        out = ['<?xml version="1.0" encoding="utf-8"?>',
               f"<!-- Generated by tools/i18n/i18n.py from tools/i18n/lang/{code}.txt — edit there. -->",
               "<resources>"]
        for key in sorted(strings):
            out.append(f'    <string name="{key}">{_xml_text(strings[key])}</string>')
        for key in sorted(plurals):
            out.append(f'    <plurals name="{key}">')
            for q, t in plurals[key].items():
                out.append(f'        <item quantity="{q}">{_xml_text(t)}</item>')
            out.append("    </plurals>")
        out.append("</resources>")
        os.makedirs(os.path.join(RES, folder), exist_ok=True)
        open(os.path.join(RES, folder, "strings.xml"), "w").write("\n".join(out) + "\n")
        missing = set(db) - set(strings) - set(plurals)
        print(f"{code}: {len(strings) + len(plurals)} strings" + (f", missing {sorted(missing)}" if missing else ""))


if __name__ == "__main__":
    write()
