"""Pre-reform Russian (до 1918): the app's Russian texts, respelled.

Not a translation but a respelling: the hard sign on the end of every word that ends in a hard
consonant, "і" before a vowel, "ѣ" (yat) where the old spelling had it, "ѳ" in "тема", the old
-ыя / -ія endings of plural adjectives, no "ё". The words that need more than the mechanical rules
are listed in WORDS (checked by hand against the app's whole vocabulary); a word not listed there
gets the mechanical rules only.
"""
import re

# word (modern, lower-case) -> the old stem (the mechanical rules are applied on top of it)
WORDS = {
    # ѣ (yat)
    "белый": "бѣлый", "где": "гдѣ", "дате": "датѣ", "действия": "дѣйствія", "деление": "дѣленіе",
    "делит": "дѣлитъ", "делить": "дѣлить", "делятся": "дѣлятся", "духе": "духѣ", "здесь": "здѣсь",
    "месте": "мѣстѣ", "место": "мѣсто", "меняется": "мѣняется", "нет": "нѣтъ", "несколько": "нѣсколько",
    "нескольких": "нѣсколькихъ", "неделя": "недѣля", "недели": "недѣли", "неизвестный": "неизвѣстный",
    "песен": "пѣсенъ", "песни": "пѣсни", "песню": "пѣсню", "песня": "пѣсня", "песням": "пѣснямъ",
    "песнями": "пѣснями", "перемешать": "перемѣшать", "подмешивать": "подмѣшивать", "после": "послѣ",
    "светлая": "свѣтлая", "светлой": "свѣтлой", "цвет": "цвѣтъ", "цвета": "цвѣта", "цветного": "цвѣтного",
    "сетка": "сѣтка", "следующая": "слѣдующая", "следующий": "слѣдующій", "следующим": "слѣдующимъ",
    "смелый": "смѣлый", "сделать": "сдѣлать", "увидеть": "увидѣть", "целиком": "цѣликомъ",
    "тем": "тѣмъ", "чем": "чѣмъ", "все": "всѣ", "всех": "всѣхъ", "внешний": "внѣшній", "внешнее": "внѣшнее",
    "далее": "далѣе", "насовсем": "насовсѣмъ", "отметить": "отмѣтить", "отмечать": "отмѣчать",
    "поделиться": "подѣлиться", "понедельник": "понедѣльникъ", "приветствие": "привѣтствіе",
    "приветствую": "привѣтствую", "раздел": "раздѣлъ", "разделы": "раздѣлы", "разделило": "раздѣлило",
    "размер": "размѣръ", "живее": "живѣе", "лиричнее": "лиричнѣе", "дружелюбнее": "дружелюбнѣе",
    # prepositional singular of nouns: -ѣ
    "музыке": "музыкѣ", "медиатеке": "медиатекѣ", "папке": "папкѣ", "странице": "страницѣ",
    "строке": "строкѣ", "плеере": "плеерѣ", "плейлисте": "плейлистѣ", "файле": "файлѣ",
    "тексте": "текстѣ", "телефоне": "телефонѣ", "устройстве": "устройствѣ", "системе": "системѣ",
    "паузе": "паузѣ", "запуске": "запускѣ", "порядке": "порядкѣ", "шторке": "шторкѣ", "повторе": "повторѣ",
    # prefixes без- / воз- / раз- kept their з
    "бесконечное": "безконечное", "воспроизведение": "возпроизведение", "воспроизведения": "возпроизведения",
    "восстановить": "возстановить",
    # ѳ in Greek words
    "тема": "ѳема", "темы": "ѳемы",
    # plural adjectives: -ыя / -ія
    "бодрые": "бодрыя", "глубокие": "глубокія", "голосовые": "голосовыя", "добавленные": "добавленныя",
    "другие": "другія", "игривые": "игривыя", "идущие": "идущія", "какие": "какія", "крупные": "крупныя",
    "мягкие": "мягкія", "недостающие": "недостающія", "общие": "общія", "парящие": "парящія",
    "первые": "первыя", "прослушиваемые": "прослушиваемыя", "прочие": "прочія",
    "скруглённые": "скругленныя", "стоящие": "стоящія", "сторонние": "стороннія", "такие": "такія",
    "яркие": "яркія", "выбранные": "выбранныя",
    # a few words from the old vocabulary
    "уведомлении": "извѣщеніи", "уведомлений": "извѣщеній", "уведомления": "извѣщенія",
    "её": "ея",
}

# units and the like that take no hard sign
KEEP = {"кб", "мб", "кгц", "кбит", "мин", "т", "п", "ч", "е", "тб", "дб", "мс"}

VOWELS = "аеёиоуыэюяѣ"
CONSONANTS = "бвгджзклмнпрстфхцчшщ"
WORD = re.compile(r"[А-Яа-яЁёѣѢіІѳѲ]+")


def _case(src: str, out: str) -> str:
    if len(src) > 1 and src.isupper():
        return out.upper()
    if src[:1].isupper():
        return out[:1].upper() + out[1:]
    return out


def _word(w: str) -> str:
    low = w.lower()
    if low in KEEP:
        return w
    base = WORDS.get(low, low)
    base = base.replace("ё", "е")
    # и → і before a vowel or й
    out = []
    for i, ch in enumerate(base):
        nxt = base[i + 1] if i + 1 < len(base) else ""
        if ch == "и" and nxt and (nxt in VOWELS or nxt == "й"):
            out.append("і")
        else:
            out.append(ch)
    base = "".join(out)
    # the hard sign after a final hard consonant
    if base and base[-1] in CONSONANTS:
        base += "ъ"
    return _case(w, base)


def convert(text: str) -> str:
    return WORD.sub(lambda m: _word(m.group(0)), text)


def write_old_russian(db: dict, res_dir: str, xml_text) -> int:
    """res/values-ru-rXP/strings.xml: every Russian text, respelled. [xml_text] escapes for XML."""
    import os
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           "<!-- Generated by tools/i18n/oldrus.py from the Russian texts — edit there. -->",
           "<resources>"]
    n = 0
    for key in sorted(db):
        e = db[key]
        if "ru" not in e:
            continue
        n += 1
        if e.get("plural"):
            out.append(f'    <plurals name="{key}">')
            for q, t in e["ru"].items():
                out.append(f'        <item quantity="{q}">{xml_text(convert(t))}</item>')
            out.append("    </plurals>")
        else:
            out.append(f'    <string name="{key}">{xml_text(convert(e["ru"]))}</string>')
    out.append("</resources>")
    folder = os.path.join(res_dir, "values-ru-rXP")
    os.makedirs(folder, exist_ok=True)
    open(os.path.join(folder, "strings.xml"), "w").write("\n".join(out) + "\n")
    return n
